(() => {
  "use strict";
  const $=id=>document.getElementById(id),esc=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const safe=value=>{try{const url=new URL(value,location.origin);return /^https?:$/.test(url.protocol)?url.href:"#";}catch{return"#";}};
  const type=new URLSearchParams(location.search).get("type")==="company"?"company":"analysis",dialog=$("editorialDialog"),article=$("editorialArticle");let items=[],visible=30;
  const card=item=>`<button type="button" class="editorial-card" data-id="${esc(item.id)}"><span class="editorial-date"><b>${esc(item.date.slice(8,10))}</b><small>${esc(item.date.slice(5,7))}월</small></span><span class="editorial-card-body"><span class="editorial-card-meta">${esc(item.eyebrow)} · 약 ${esc(item.read_minutes)}분</span><strong>${esc(item.title)}</strong><span class="editorial-card-summary">${esc(item.summary)}</span><span class="editorial-card-tags">${(item.tags||[]).slice(0,3).map(tag=>`<span>${esc(tag)}</span>`).join("")}</span></span><span class="editorial-arrow">›</span></button>`;
  const metrics=rows=>rows?.length?`<div class="editorial-metrics">${rows.map(row=>`<div><span>${esc(row.label)}</span><b>${esc(row.value)}</b><small>${esc(row.note||"")}</small></div>`).join("")}</div>`:"";
  const detail=item=>window.EditorialReport?window.EditorialReport.render(item,{kind:type}):`<header class="editorial-article-head"><h2 id="editorialDialogTitle">${esc(item.title)}</h2><p>${esc(item.summary)}</p></header>${metrics(item.metrics)}`;
  function render(){const query=$("analysisSearch").value.trim().toLowerCase(),filtered=items.filter(item=>!query||[item.title,item.summary,item.eyebrow,...(item.tags||[])].join(" ").toLowerCase().includes(query)),shown=filtered.slice(0,visible);$("analysisCount").textContent=`전체 ${filtered.length}건 중 ${shown.length}건 표시`;$("analysisGrid").innerHTML=shown.length?shown.map(card).join(""):'<p class="news-empty">조건에 맞는 분석이 없습니다.</p>';$("analysisMore").hidden=shown.length>=filtered.length;$("analysisGrid").querySelectorAll("[data-id]").forEach(button=>button.onclick=()=>{const item=items.find(row=>row.id===button.dataset.id);article.innerHTML=detail(item);dialog.showModal();document.body.classList.add("dialog-open");});}
  $("analysisTitle").textContent=type==="company"?"기업분석":"심층분석";$("analysisIntro").textContent=type==="company"?"주요 기업의 사업구조, 최근 이슈, 기회·위험과 다음 공시 확인값을 정리합니다.":"여러 매체의 주요 이슈를 원인, 전파경로, 시나리오와 확인지표로 재구성합니다.";document.querySelector(`[data-type="${type}"]`)?.classList.add("active");
  Promise.all([fetch("content/analysis/index.json?v=2",{cache:"no-store"}).then(r=>r.json()),fetch("content/editorial.json?v=2",{cache:"no-store"}).then(r=>r.json())]).then(([auto,manual])=>{const key=type==="company"?"company_items":"analysis_items",section=(manual.sections||[]).find(row=>row.id===type);items=[...(auto[key]||[]),...(section?.items||[])].filter((item,index,rows)=>rows.findIndex(row=>row.id===item.id)===index);$("analysisUpdated").textContent=`${auto.lookback_days||0}일 자료 · ${items.length}건`;let status=$("dailyCompanyStatus");if(!status){status=document.createElement("p");status.id="dailyCompanyStatus";document.querySelector(".news-page-head")?.after(status);}const daily=auto.daily_company_selection;if(type==="company"&&daily?.message){status.hidden=false;status.className=`daily-company-status ${daily.status==="published"?"published":"empty"}`;status.textContent=`${daily.date} · ${daily.message}`;}else status.hidden=true;render();}).catch(error=>{$("analysisGrid").innerHTML=`<p class="news-empty">${esc(error.message)}</p>`;});
  $("analysisSearch").oninput=()=>{visible=30;render();};$("analysisMore").onclick=()=>{visible+=30;render();};dialog.querySelector(".editorial-dialog-close").onclick=()=>dialog.close();dialog.onclick=event=>{if(event.target===dialog)dialog.close();};dialog.onclose=()=>document.body.classList.remove("dialog-open");
})();
