(() => {
  "use strict";
  const $ = id => document.getElementById(id), esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const safe = value => { try { const url = new URL(value, location.origin); return /^https?:$/.test(url.protocol) ? url.href : "#"; } catch { return "#"; } };
  const dialog=$("editorialDialog"), article=$("editorialArticle"); let items=[],archives=[],currentPage=1,activeCategory="",activeSource="";
  const categories=["전체","증시","금리·채권","환율","원자재","산업·기업","거시경제","부동산","가상자산"];
  const fallbackScore=item=>{const text=`${item.title||""} ${(item.tags||[]).join(" ")}`.toLowerCase(),core=["증시","금리·채권","환율","원자재"].includes(item.category||item.tags?.[0]),keywords=["기준금리","연준","환율","국채","물가","고용","gdp","관세","수출","실적","코스피","코스닥","나스닥","유가","원유","반도체","대출 규제","세제"],noise=["화재","사망","숨져","대피","홍수","실종","범죄"];return 11+(core?14:8)+Math.min(18,keywords.filter(k=>text.includes(k)).length*3)+(noise.some(k=>text.includes(k))?-32:0);};
  const isImportant=item=>item.important===true||(item.important===undefined&&Number(item.importance_score||fallbackScore(item))>=28);
  const categoryOf=item=>item.category||(item.tags||[])[0]||"거시경제";
  const sourceOf=item=>item.publisher||item.sources?.[0]?.publisher||(item.tags||[])[1]||"원문";
  const card = item => `<article class="news-archive-card"><time datetime="${esc(item.date)}">${esc(String(item.date||"").slice(5).replace("-","."))}</time><div class="news-archive-body"><div class="news-card-taxonomy"><button type="button" data-category="${esc(categoryOf(item))}">#${esc(categoryOf(item))}</button><button type="button" data-source="${esc(sourceOf(item))}">${esc(sourceOf(item))}</button></div><button type="button" class="news-title-button" data-id="${esc(item.id)}"><strong>${isImportant(item)?'<span class="important-prefix">[중요]</span> ':''}${esc(item.title)}</strong><span>${esc(item.summary)}</span></button></div></article>`;
  const detail = item => window.EditorialReport ? window.EditorialReport.render(item,{kind:"news"}) : `<header class="editorial-article-head"><h2 id="editorialDialogTitle">${esc(item.title)}</h2><p>${esc(item.summary)}</p></header>`;
  function pageLinks(){const total=archives.length,href=page=>`?page=${page}${activeCategory?`&category=${encodeURIComponent(activeCategory)}`:""}`,link=page=>`<a href="${href(page)}" class="${page===currentPage?"active":""}" aria-label="${page}페이지${page===currentPage?" 현재":""}">${page}</a>`;let links=Array.from({length:Math.min(5,total)},(_,index)=>link(index+1));if(total>5)links.push('<span class="news-page-ellipsis" aria-hidden="true">…</span>',link(total));const make=()=>`<div class="news-page-list">${links.join("")}</div><form class="news-page-jump"><label>페이지 이동 <input type="number" min="1" max="${total}" value="${currentPage}" inputmode="numeric" aria-label="이동할 페이지 번호"></label><button type="submit">이동</button></form>`;$("newsPaginationTop").innerHTML=make();$("newsPaginationBottom").innerHTML=make();document.querySelectorAll(".news-page-jump").forEach(form=>form.onsubmit=event=>{event.preventDefault();const requested=Number(form.querySelector("input").value);if(!Number.isFinite(requested))return;location.href=href(Math.min(total,Math.max(1,Math.trunc(requested))));});}
  function categoryChips(){$("newsCategories").innerHTML=categories.map(category=>`<button type="button" data-filter-category="${category==="전체"?"":esc(category)}" class="${activeCategory===(category==="전체"?"":category)?"active":""}">${category}</button>`).join("");$("newsCategories").querySelectorAll("[data-filter-category]").forEach(button=>button.onclick=()=>{activeCategory=button.dataset.filterCategory;activeSource="";categoryChips();pageLinks();render();});}
  function render(){const query=$("newsSearch").value.trim().toLowerCase();const filtered=items.filter(item=>(!activeCategory||categoryOf(item)===activeCategory)&&(!activeSource||sourceOf(item)===activeSource)&&(!query||[item.title,item.summary,item.eyebrow,sourceOf(item),...(item.tags||[])].join(" ").toLowerCase().includes(query)));const archive=archives[currentPage-1];$("newsCount").textContent=`${archive?.date||""} · 전체 ${items.length.toLocaleString()}건 중 ${filtered.length.toLocaleString()}건 표시`;$("newsActiveFilter").textContent=activeSource?`출처: ${activeSource}`:activeCategory?`카테고리: ${activeCategory}`:"전체 카테고리";$("newsGrid").innerHTML=filtered.length?filtered.map(card).join(""):'<p class="news-empty">조건에 맞는 기사가 없습니다.</p>';$("newsGrid").querySelectorAll("[data-id]").forEach(button=>button.onclick=()=>{const item=items.find(row=>row.id===button.dataset.id);article.innerHTML=detail(item);dialog.showModal();document.body.classList.add("dialog-open");});$("newsGrid").querySelectorAll("[data-category]").forEach(button=>button.onclick=()=>{activeCategory=button.dataset.category;activeSource="";categoryChips();pageLinks();render();});$("newsGrid").querySelectorAll("[data-source]").forEach(button=>button.onclick=()=>{activeSource=button.dataset.source;render();});}
  dialog.querySelector(".editorial-dialog-close").onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close();};dialog.onclose=()=>document.body.classList.remove("dialog-open");
  async function load(){const response=await fetch("content/news/index.json?v=4",{cache:"no-store"});if(!response.ok)throw Error("뉴스를 불러오지 못했습니다.");const data=await response.json();archives=data.archives||[];currentPage=Math.min(Math.max(1,Number(new URLSearchParams(location.search).get("page"))||1),Math.max(1,archives.length));activeCategory=new URLSearchParams(location.search).get("category")||"";const archive=archives[currentPage-1];if(archive){const day=await fetch(`content/news/${encodeURIComponent(archive.file)}?v=4`,{cache:"no-store"});if(!day.ok)throw Error("선택한 날짜의 뉴스를 불러오지 못했습니다.");items=(await day.json()).items||[];}else items=data.items||[];$("newsUpdated").textContent=`${data.archive_days||0}일 · ${(data.total_articles||0).toLocaleString()}건`;pageLinks();categoryChips();render();}
  load().catch(error=>{$("newsGrid").innerHTML=`<p class="news-empty">${esc(error.message)}</p>`;});
  $("newsSearch").oninput=render;$("newsReset").onclick=()=>{$("newsSearch").value="";activeCategory="";activeSource="";categoryChips();pageLinks();render();};
})();
