(() => {
  "use strict";
  const $ = id => document.getElementById(id), esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
  const safe = value => { try { const url = new URL(value, location.origin); return /^https?:$/.test(url.protocol) ? url.href : "#"; } catch { return "#"; } };
  const dialog=$("editorialDialog"), article=$("editorialArticle"); let items=[],visible=40,archives=[];
  const card = item => `<button type="button" class="editorial-card" data-id="${esc(item.id)}"><span class="editorial-date"><b>${esc(item.date.slice(8,10))}</b><small>${esc(item.date.slice(5,7))}월</small></span><span class="editorial-card-body"><span class="editorial-card-meta">${esc(item.eyebrow)} · 약 ${esc(item.read_minutes)}분</span><strong>${esc(item.title)}</strong><span class="editorial-card-summary">${esc(item.summary)}</span><span class="editorial-card-tags">${(item.tags||[]).slice(0,3).map(tag=>`<span>${esc(tag)}</span>`).join("")}</span></span><span class="editorial-arrow">›</span></button>`;
  const detail = item => window.EditorialReport ? window.EditorialReport.render(item,{kind:"news"}) : `<header class="editorial-article-head"><h2 id="editorialDialogTitle">${esc(item.title)}</h2><p>${esc(item.summary)}</p></header>`;
  function render(){const query=$("newsSearch").value.trim().toLowerCase(),date=$("newsDate").value;const filtered=items.filter(item=>(!date||(item.archive_date||item.date)===date)&&(!query||[item.title,item.summary,item.eyebrow,...(item.tags||[])].join(" ").toLowerCase().includes(query)));const shown=filtered.slice(0,visible);$("newsCount").textContent=`전체 ${filtered.length.toLocaleString()}건 중 ${shown.length.toLocaleString()}건 표시`;$("newsGrid").innerHTML=shown.length?shown.map(card).join(""):'<p class="news-empty">조건에 맞는 기사가 없습니다.</p>';$("newsMore").hidden=shown.length>=filtered.length;$("newsGrid").querySelectorAll("[data-id]").forEach(button=>button.onclick=()=>{const item=items.find(row=>row.id===button.dataset.id);article.innerHTML=detail(item);dialog.showModal();document.body.classList.add("dialog-open");});}
  dialog.querySelector(".editorial-dialog-close").onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close();};dialog.onclose=()=>document.body.classList.remove("dialog-open");
  fetch("content/news/index.json?v=2",{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("뉴스를 불러오지 못했습니다.");return r.json();}).then(data=>{items=data.items||[];archives=data.archives||[];$("newsUpdated").textContent=`${data.archive_days||0}일 · ${(data.total_articles||0).toLocaleString()}건`;$("newsDate").innerHTML+=archives.map(a=>`<option value="${esc(a.date)}">${esc(a.date)} (${a.count}건)</option>`).join("");render();}).catch(error=>{$("newsGrid").innerHTML=`<p class="news-empty">${esc(error.message)}</p>`;});
  $("newsSearch").oninput=()=>{visible=40;render();};$("newsDate").onchange=async()=>{visible=40;const selected=$("newsDate").value;if(selected){const archive=archives.find(row=>row.date===selected);if(archive){const response=await fetch(`content/news/${encodeURIComponent(archive.file)}?v=2`,{cache:"no-store"});if(response.ok){const data=await response.json();items=[...items.filter(item=>item.archive_date!==selected),...(data.items||[]).map(item=>({...item,archive_date:selected}))];}}}render();};$("newsMore").onclick=()=>{visible+=40;render();};
})();
